name: "Validate Gradle Wrapper"
on: [push, pull_request]
permissions:
  contents: read
jobs:
  validation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3 #v4.4.2
